# Generated by Django 4.2.7 on 2025-09-12 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for QR code",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this storage session",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Items in Storage"),
                            ("claimed", "Claimed - Items Retrieved"),
                            ("expired", "Expired - Session Ended"),
                            ("cancelled", "Cancelled - Session Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When items were stored"
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, help_text="When items were claimed", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last modification time"
                    ),
                ),
                (
                    "qr_code_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data for QR code display",
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical storage location (e.g., Shelf A-1)",
                        max_length=100,
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for storage staff"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_entries",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Entry",
                "verbose_name_plural": "Storage Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(help_text="Name of the item", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("books", "Books & Study Materials"),
                            ("electronics", "Electronics & Gadgets"),
                            ("clothing", "Clothing & Personal Items"),
                            ("stationery", "Stationery & Supplies"),
                            ("sports", "Sports Equipment"),
                            ("misc", "Miscellaneous"),
                        ],
                        default="misc",
                        help_text="Item category for organization",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of this item"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description, color, brand, etc."
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated value in INR (optional)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "storage_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="storage.storageentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stored Item",
                "verbose_name_plural": "Stored Items",
                "ordering": ["category", "item_name"],
                "indexes": [
                    models.Index(
                        fields=["storage_entry", "category"],
                        name="storage_sto_storage_afc71e_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="storageentry",
            index=models.Index(
                fields=["student", "status"], name="storage_sto_student_5779b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storageentry",
            index=models.Index(
                fields=["status", "created_at"], name="storage_sto_status_50c926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storageentry",
            index=models.Index(
                fields=["entry_id"], name="storage_sto_entry_i_fb8421_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storageentry",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["active", "expired", "cancelled"]),
                    models.Q(("claimed_at__isnull", False), ("status", "claimed")),
                    _connector="OR",
                ),
                name="claimed_at_required_when_claimed",
            ),
        ),
    ]
