# Generated by Django 4.2.7 on 2025-09-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_studentprofile_department"),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageentry",
            name="student",
            field=models.ForeignKey(
                help_text="Student who owns these items",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_entries",
                to="accounts.studentprofile",
            ),
        ),
    ]
