# Generated by Django 4.2.7 on 2025-09-12 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCodeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data embedded in the QR code",
                    ),
                ),
                (
                    "storage_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="storage.storageentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Image",
                "verbose_name_plural": "QR Code Images",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="QRScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=False)),
                ("action_taken", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="unique_codes.qrcodeimage",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Scan",
                "verbose_name_plural": "QR Code Scans",
                "ordering": ["-scanned_at"],
            },
        ),
    ]
