# Generated by Django 4.2.7 on 2026-02-03 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0002_alter_storageentry_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Unique alphanumeric code for manual verification', max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_data', models.JSONField(blank=True, default=dict, help_text='Data metadata')),
                ('storage_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='storage.storageentry')),
            ],
            options={
                'verbose_name': 'Unique Code',
                'verbose_name_plural': 'Unique Codes',
                'db_table': 'qr_codes_qrcodeimage',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UniqueCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='unique_codes.uniquecode')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Scan',
                'verbose_name_plural': 'Code Scans',
                'db_table': 'qr_codes_qrscan',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
