# Generated by Django 4.2.7 on 2026-02-04 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_storageentry_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unique_codes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniquecodescan',
            old_name='qr_code',
            new_name='unique_code',
        ),
        migrations.AlterField(
            model_name='uniquecode',
            name='storage_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unique_code', to='storage.storageentry'),
        ),
        migrations.AlterField(
            model_name='uniquecodescan',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_scans', to=settings.AUTH_USER_MODEL),
        ),
    ]
