# Generated by Django 4.2.7 on 2026-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodeimage',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Unique Code', 'verbose_name_plural': 'Unique Codes'},
        ),
        migrations.AlterModelOptions(
            name='qrscan',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Code Scan', 'verbose_name_plural': 'Code Scans'},
        ),
        migrations.AddField(
            model_name='qrcodeimage',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique alphanumeric code for manual verification', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeimage',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data metadata'),
        ),
    ]
