# Generated by Django 4.2.7 on 2026-02-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique_codes', '0002_alter_qrcodeimage_options_alter_qrscan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeimage',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='0000-0000', help_text='Unique alphanumeric code for manual verification', max_length=20, unique=True),
        ),
    ]
