# Generated by Django 4.2.7 on 2025-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("CSE", "Computer Science & Engineering"),
                    ("ECE", "Electronics & Communication Engineering"),
                    ("AIDS", "Artificial Intelligence & Data Science"),
                    ("CSY", "Cyber Security"),
                    ("CIVIL", "Civil Engineering"),
                    ("IT", "Information Technology"),
                    ("OTHER", "Other"),
                ],
                help_text="Academic department",
                max_length=10,
            ),
        ),
    ]
