# Generated by Django 4.2.7 on 2025-09-15 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_studentprofile_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="roll_number",
            field=models.CharField(
                db_index=True,
                help_text="Format: 2024BCS0001, 2024BCY0002, 2024BCD0003, 2024BEC0004",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Roll number format: Format: 2024BCS0001, 2024BCY0002, 2024BCD0003, 2024BEC0004",
                        regex="^(20(?:2[4-9]|[3-9][0-9]))B(CS|CY|CD|EC)([0-9]{4})$",
                    )
                ],
            ),
        ),
    ]
